/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisItem: typeof import('./../components/common/analysisItem/index.vue')['default']
    AnalysisItemIcon: typeof import('./../components/Icons/analysisItemIcon/index.vue')['default']
    ColorPicker: typeof import('./../components/common/colorPicker/index.vue')['default']
    EChart: typeof import('./../components/EChart/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElText: typeof import('element-plus/es')['ElText']
    GroupNode: typeof import('./../components/vueFlow/components/groupNode/index.vue')['default']
    Highlight: typeof import('./../components/common/highlight/index.vue')['default']
    HomePageIcon: typeof import('./../components/Icons/HomePageIcon/index.vue')['default']
    Icon: typeof import('./../components/vueFlow/components/ideaNode/components/icon/index.vue')['default']
    IdeaNode: typeof import('./../components/vueFlow/components/ideaNode/index.vue')['default']
    Lottie: typeof import('./../components/common/lottie/index.vue')['default']
    ManageHeader: typeof import('./../components/common/manageHeader/index.vue')['default']
    ManagePageIcon: typeof import('./../components/Icons/ManagePageIcon/index.vue')['default']
    MemberAnalysis: typeof import('./../components/common/memberAnalysis/index.vue')['default']
    MyAlert: typeof import('./../components/ElementPlusPackage/MyAlert.vue')['default']
    MyButton: typeof import('./../components/ElementPlusPackage/MyButton.vue')['default']
    NodePopover: typeof import('./../components/NodePopover/index.vue')['default']
    RadarGraph: typeof import('./../components/common/radarGraph/index.vue')['default']
    RelationshipGraph: typeof import('./../components/common/relationshipGraph/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalkCard: typeof import('./../components/common/talkCard/index.vue')['default']
    TopicNode: typeof import('./../components/vueFlow/components/topicNode/index.vue')['default']
    VueFlow: typeof import('./../components/vueFlow/index.vue')['default']
    WaveAnimation: typeof import('./../components/common/waveAnimation/index.vue')['default']
    WordCloud: typeof import('./../components/common/wordCloud/index.vue')['default']
  }
}
