/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./../components/Node/demo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    FlowIcon: typeof import('./../components/Icon/flowIcon.vue')['default']
    GroupNode: typeof import('./../components/Node/groupNode/index.vue')['default']
    HomePageIcon: typeof import('./../components/Icons/HomePageIcon/index.vue')['default']
    Icon: typeof import('./../components/Icon/index.vue')['default']
    Icons: typeof import('./../components/Icons/index.vue')['default']
    IdeaNode: typeof import('./../components/Node/ideaNode/index.vue')['default']
    LoginImg: typeof import('./../components/common/loginImg/index.vue')['default']
    Lottie: typeof import('./../components/common/lottie/index.vue')['default']
    ManagePageIcon: typeof import('./../components/Icons/ManagePageIcon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopicNode: typeof import('./../components/Node/topicNode/index.vue')['default']
    VueFlow: typeof import('./../components/vueFlow/index.vue')['default']
  }
}
