/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./../components/Node/demo.vue')['default']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    FloatButtonGroup: typeof import('./../components/common/floatButtonGroup.vue')['default']
    FlowIcon: typeof import('./../components/Icon/flowIcon.vue')['default']
    GroupNode: typeof import('./../components/Node/groupNode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopicNode: typeof import('./../components/Node/topicNode.vue')['default']
    VueFlow: typeof import('./../components/vueFlow/index.vue')['default']
  }
}
